<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>tv.game88</groupId>
        <artifactId>game88-server</artifactId>
        <version>1.0</version>
    </parent>

    <groupId>tv.game88.game</groupId>
    <artifactId>game88-game</artifactId>
    <packaging>pom</packaging>

    <name>Game88 Server Game Parent</name>
    <description>88棋牌服务-三方游戏以及自研游戏等服务</description>

    <modules>
        <module>game88-game-api</module>
        <module>game88-game-admin</module>
        <module>game88-game-app</module>
    </modules>
</project>
