<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>tv.game88.wallet</groupId>
        <artifactId>game88-wallet</artifactId>
        <version>1.0</version>
    </parent>

    <artifactId>game88-wallet-app</artifactId>

    <name>Game88 Server Wallet App</name>
    <description>88棋牌服务-虚拟钱包App服务</description>

    <dependencies>
        <dependency>
            <groupId>tv.game88.wallet</groupId>
            <artifactId>game88-wallet-api</artifactId>
            <version>1.0</version>
        </dependency>

        <dependency>
            <groupId>tv.game88.common</groupId>
            <artifactId>game88-common-security</artifactId>
            <version>1.0</version>
        </dependency>

        <!--Token生成与解析-->
        <dependency>
            <groupId>io.jsonwebtoken</groupId>
            <artifactId>jjwt-api</artifactId>
        </dependency>
        <dependency>
            <groupId>io.jsonwebtoken</groupId>
            <artifactId>jjwt-impl</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>io.jsonwebtoken</groupId>
            <artifactId>jjwt-jackson</artifactId>
            <scope>runtime</scope>
        </dependency>

        <dependency>
            <groupId>tv.game88.common</groupId>
            <artifactId>game88-common-swagger</artifactId>
            <version>1.0</version>
        </dependency>

        <!-- spring freemarker 模板引擎 -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-freemarker</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
    </dependencies>
</project>