package tv.game88.game.api.dto;

import lombok.Data;

import javax.validation.constraints.NotNull;
import java.util.StringJoiner;

@Data
public class ReqPGSoftGameData {

    @NotNull( message = "Unique Identity of Operator" )
    private String operator_token;
    @NotNull(message = "Shared passphrase between PGSoft and operator")
    private String secret_key;
    @NotNull(message = "Token generated by operator system")
    private String operator_player_session;
    @NotNull(message = "Custom param")
    private String custom_parameter;

    @Override
    public String toString() {
        return new StringJoiner(", ", ReqPGSoftGameData.class.getSimpleName() + "[", "]")
                .add("operator_token='" + operator_token + "'")
                .add("secret_key='" + secret_key + "'")
                .add("operator_player_session='" + operator_player_session + "'")
                .add("custom_parameter='" + custom_parameter + "'")
                .toString();
    }
}
