spring:
  datasource:
    dynamic:
      datasource:
        master:
          url: jdbc:mysql://moli-dandu.cluster-c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/general?serverTimezone=Asia/Shanghai&useSSL=false&autoReconnect=true&failOverReadOnly=false
          username: admin
          password: dRmBstReqberz!14Xm#
        slave-7701:
          url: jdbc:mysql://back01.cluster-ro-c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/db_cx001?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
          username: admin
          password: djkteCbsupY3RCDkPDPS
        slave-7702:
          url: jdbc:mysql://back01.cluster-ro-c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/7702_main?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
          username: admin
          password: djkteCbsupY3RCDkPDPS
        slave-7703:
          url: jdbc:mysql://back01.cluster-ro-c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/7703_main?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
          username: admin
          password: djkteCbsupY3RCDkPDPS
        slave-7704:
          url: jdbc:mysql://back01.cluster-ro-c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/7704_main?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
          username: admin
          password: djkteCbsupY3RCDkPDPS
        slave-7705:
          url: jdbc:mysql://back01.cluster-ro-c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/7704_main?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
          username: admin
          password: djkteCbsupY3RCDkPDPS
        slave-7706:
          url: jdbc:mysql://back01.cluster-ro-c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/7706_main?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
          username: admin
          password: djkteCbsupY3RCDkPDPS
        slave-7707:
          url: jdbc:mysql://back01.cluster-ro-c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/7707_main?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
          username: admin
          password: djkteCbsupY3RCDkPDPS
        slave-7708:
          url: jdbc:mysql://moli-dandu.cluster-c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/7708_main?useUnicode=true&allowMultiQueries=true
          username: admin
          password: dRmBstReqberz!14Xm#
        slave-7709:
          url: jdbc:mysql://rdsdb-7709.c6uwqqgyc6gv.ap-northeast-1.rds.amazonaws.com:3306/7709_main?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
          username: ENC(Oio1NRHNaaJOZR97fZvEaY5UE+D4oBpvlSGzCsbr1s6vbPVXecQ3/IEKVIdSPyjq)
          password: ENC(+CdDSfBay8eP/qc4mf/yPve5LsUgY6SMz9+J6u5vJDkjQIe3sUu/+atlTXrhHIa6JzjUJYFE2Ni8pp5nSnpiiQ==)
        slave-7710:
          url: jdbc:mysql://moli-dandu.cluster-c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/7710_main?useUnicode=true&allowMultiQueries=true
          username: admin
          password: dRmBstReqberz!14Xm#
        slave-7711:
          url: jdbc:mysql://sevenall.cluster-c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/7711_main?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
          username: admin
          password: dRmBstReqberz!14Xm#
        slave-77yutu:
          url: jdbc:mysql://back01.cluster-ro-c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/77yutu_main?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
          username: admin
          password: djkteCbsupY3RCDkPDPS
        slave-77jp:
          url: jdbc:mysql://sevenall.cluster-c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/77jp_main?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
          username: admin
          password: dRmBstReqberz!14Xm#
        slave-77xy:
          url: jdbc:mysql://sevenall.cluster-c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/77xy_main?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
          username: admin
          password: dRmBstReqberz!14Xm#
        slave-77ml:
          url: jdbc:mysql://sevenall.cluster-c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/77ml_main?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
          username: admin
          password: dRmBstReqberz!14Xm#
        slave-77je:
          url: jdbc:mysql://back01.cluster-ro-c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/77je_main?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
          username: admin
          password: djkteCbsupY3RCDkPDPS
        slave-77yt:
          url: jdbc:mysql://sevenall.cluster-c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/77yt_main?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
          username: admin
          password: dRmBstReqberz!14Xm#
        slave-88ky:
          url: jdbc:mysql://back01.cluster-ro-c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/88ky?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
          username: admin
          password: djkteCbsupY3RCDkPDPS
        slave-88vns:
          url: jdbc:mysql://qp02-instance-1.c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/88ky2?useUnicode=true&allowMultiQueries=true
          username: admin
          password: dRmBstReqberz!14Xm#
        slave-77bl:
          url: jdbc:mysql://livedata.cluster-c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/77bl_main?useUnicode=true&allowMultiQueries=true
          username: admin
          password: dRmBstReqberz!14Xm#
        slave-77miai:
          url: jdbc:mysql://livedata.cluster-c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/77miai_main?useUnicode=true&allowMultiQueries=true
          username: admin
          password: dRmBstReqberz!14Xm#
        slave-77mt:
          url: jdbc:mysql://livedata.cluster-c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/77mt_main?useUnicode=true&allowMultiQueries=true
          username: admin
          password: dRmBstReqberz!14Xm#
        slave-77wm:
          url: jdbc:mysql://livedata.cluster-c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/77wm_main?useUnicode=true&allowMultiQueries=true
          username: admin
          password: dRmBstReqberz!14Xm#
        slave-77cp:
          url: jdbc:mysql://livedata.cluster-c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/77cp_main?useUnicode=true&allowMultiQueries=true
          username: admin
          password: dRmBstReqberz!14Xm#
  redis:
    host: zongdaili.zczoyz.ng.0001.ape1.cache.amazonaws.com
    port: 6379
