spring:
  datasource:
    dynamic:
      datasource:
        master:
          url: jdbc:mysql://moli-dandu.cluster-c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/general?serverTimezone=Asia/Shanghai&useSSL=false&autoReconnect=true&failOverReadOnly=false
          username: admin
          password: dRmBstReqberz!14Xm#
        slave_7701:
          url: jdbc:mysql://back01.cluster-ro-c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/db_cx001?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
          username: admin
          password: djkteCbsupY3RCDkPDPS
        slave_7702:
          url: jdbc:mysql://back01.cluster-ro-c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/7702_main?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
          username: admin
          password: djkteCbsupY3RCDkPDPS
        slave_7703:
          url: jdbc:mysql://back01.cluster-ro-c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/7703_main?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
          username: admin
          password: djkteCbsupY3RCDkPDPS
        slave_7704:
          url: jdbc:mysql://back01.cluster-ro-c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/7704_main?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
          username: admin
          password: djkteCbsupY3RCDkPDPS
        slave_7705:
          url: jdbc:mysql://back01.cluster-ro-c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/7705_main?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
          username: admin
          password: djkteCbsupY3RCDkPDPS
        slave_7706:
          url: jdbc:mysql://back01.cluster-ro-c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/7706_main?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
          username: admin
          password: djkteCbsupY3RCDkPDPS
        slave_7707:
          url: jdbc:mysql://back01.cluster-ro-c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/7707_main?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
          username: admin
          password: djkteCbsupY3RCDkPDPS
        slave_7708:
          url: jdbc:mysql://moli-dandu.cluster-c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/7708_main?useUnicode=true&allowMultiQueries=true
          username: admin
          password: dRmBstReqberz!14Xm#
        slave_7709:
          url: jdbc:mysql://rdsdb-7709.c6uwqqgyc6gv.ap-northeast-1.rds.amazonaws.com:3306/7709_main?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
          username: seldata
          password: 5eypHP13jn2Nvaqgfd
        slave_7710:
          url: jdbc:mysql://moli-dandu.cluster-c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/7710_main?useUnicode=true&allowMultiQueries=true
          username: admin
          password: dRmBstReqberz!14Xm#
        slave_7711:
          url: jdbc:mysql://sevenall.cluster-c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/7711_main?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
          username: admin
          password: dRmBstReqberz!14Xm#
        slave_77yutu:
          url: jdbc:mysql://back01.cluster-ro-c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/77yutu_main?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
          username: admin
          password: djkteCbsupY3RCDkPDPS
        slave_77jp:
          url: jdbc:mysql://sevenall.cluster-c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/77jp_main?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
          username: admin
          password: dRmBstReqberz!14Xm#
        slave_77xy:
          url: jdbc:mysql://sevenall.cluster-c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/77xy_main?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
          username: admin
          password: dRmBstReqberz!14Xm#
        slave_77ml:
          url: jdbc:mysql://sevenall.cluster-c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/77ml_main?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
          username: admin
          password: dRmBstReqberz!14Xm#
        slave_77je:
          url: jdbc:mysql://back01.cluster-ro-c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/77je_main?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
          username: admin
          password: djkteCbsupY3RCDkPDPS
        slave_88ky:
          url: jdbc:mysql://back01.cluster-ro-c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/88ky?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
          username: admin
          password: djkteCbsupY3RCDkPDPS
        slave_88vns:
          url: jdbc:mysql://qp02-instance-1.c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/88ky2?useUnicode=true&allowMultiQueries=true
          username: admin
          password: dRmBstReqberz!14Xm#
        slave_77bl:
          url: jdbc:mysql://livedata.cluster-c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/77bl_main?useUnicode=true&allowMultiQueries=true
          username: admin
          password: dRmBstReqberz!14Xm#
        slave_77mt:
          url: jdbc:mysql://livedata.cluster-c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/77mt_main?useUnicode=true&allowMultiQueries=true
          username: admin
          password: dRmBstReqberz!14Xm#
        slave_77wm:
          url: jdbc:mysql://livedata.cluster-c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/77wm_main?useUnicode=true&allowMultiQueries=true
          username: admin
          password: dRmBstReqberz!14Xm#
        slave_77baby:
          url: jdbc:mysql://livedata.cluster-c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/77baby_main?useUnicode=true&allowMultiQueries=true
          username: admin
          password: dRmBstReqberz!14Xm#
        slave_77mj:
          url: jdbc:mysql://sevenall.cluster-c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/77mj_main?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
          username: admin
          password: dRmBstReqberz!14Xm#
        slave_9901:
          url: jdbc:mysql://r99.cluster-ctsokuok0ohz.ap-southeast-3.rds.amazonaws.com/9901?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
          username: admin
          password: 3WMX&YMHXEthQ$ed
        slave_9906:
          url: jdbc:mysql://r99.cluster-ctsokuok0ohz.ap-southeast-3.rds.amazonaws.com/9906?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
          username: admin
          password: 3WMX&YMHXEthQ$ed
        slave_9907:
          url: jdbc:mysql://r99-2.cluster-ctsokuok0ohz.ap-southeast-3.rds.amazonaws.com/9907?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
          username: admin
          password: 3W1MX&Y32M1HdXEthQ$edd
        slave_9908:
          url: jdbc:mysql://r99-2.cluster-ctsokuok0ohz.ap-southeast-3.rds.amazonaws.com/9908?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
          username: admin
          password: 3W1MX&Y32M1HdXEthQ$edd
        slave_9909:
          url: jdbc:mysql://r9909.cluster-ctsokuok0ohz.ap-southeast-3.rds.amazonaws.com/9909?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
          username: admin
          password: 3W1MX&Y32M1HdXE12thQ$edd
  data:
    redis:
      host: zongdaili.zczoyz.ng.0001.ape1.cache.amazonaws.com
      port: 6379

