<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>game88-game</artifactId>
        <groupId>tv.game88.game</groupId>
        <version>1.0</version>
    </parent>

    <artifactId>game88-game-api</artifactId>

    <name>Game88 Server Game Api</name>
    <description>88棋牌服务-三方游戏API服务</description>

    <dependencies>
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>dynamic-datasource-spring-boot3-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>tv.game88.core</groupId>
            <artifactId>game88-core-game</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>tv.game88.core</groupId>
            <artifactId>game88-core-member</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>tv.game88.core</groupId>
            <artifactId>game88-core-quest</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>tv.game88.core</groupId>
            <artifactId>game88-core-lottery</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>tv.game88.core</groupId>
            <artifactId>game88-core-telegramBot</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>tv.game88.common</groupId>
            <artifactId>game88-common-http</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.retry</groupId>
            <artifactId>spring-retry</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-aspects</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
