spring:
  datasource:
    url: jdbc:mysql://43.199.95.227:3306/8800?serverTimezone=Asia/Shanghai&useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: root
    password: f:e=h>EVUH,!N7zS&J`9
  data:
    redis:
      host: 43.199.95.227
      port: 6379
      password: EvYsN39ViArDumx4pWyH
      database: 2

## 彩票奖池代理
lotteryCenter : 8800

springdoc:
  api-docs:
    enabled: true

#mybatis-plus:
  #configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
