<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>tv.game88.general</groupId>
        <artifactId>game88-general</artifactId>
        <version>1.0</version>
    </parent>

    <artifactId>game88-general-admin</artifactId>
    <packaging>jar</packaging>

    <name>Game88 Server General Admin</name>
    <description>88棋牌服务-总代以及三方游戏拉取Admin服务</description>

    <dependencies>
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>dynamic-datasource-spring-boot-starter</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>tv.game88.general</groupId>
            <artifactId>game88-general-api</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>tv.game88.core</groupId>
            <artifactId>game88-core-admin</artifactId>
            <version>1.0</version>
        </dependency>
    </dependencies>
</project>
