spring:
  datasource:
    url: jdbc:mysql://8.210.10.193:3306/general?serverTimezone=Asia/Shanghai&useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: root
    password: f:e=h>EVUH,!N7zS&J`9
  data:
    redis:
      host: 8.210.10.193
      port: 6379
      password: EvYsN39ViArDumx4pWyH
      database: 3

#mybatis-plus:
  #configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
