spring:
  datasource:
    dynamic:
      datasource:
        master:
          url: jdbc:mysql://qp02-instance-1.c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/8803?serverTimezone=Asia/Shanghai&useSSL=false&autoReconnect=true&failOverReadOnly=false
          username: admin
          password: dRmBstReqberz!14Xm#
        secondary:
          url: jdbc:mysql://moli-dandu.cluster-c2mgsz0wk6v3.ap-east-1.rds.amazonaws.com:3306/general?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
          username: admin
          password: dRmBstReqberz!14Xm#
  data:
    redis:
      host: ky8803.zczoyz.ng.0001.ape1.cache.amazonaws.com
      port: 6379
