<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>tv.game88</groupId>
        <artifactId>game88-server</artifactId>
        <version>1.0</version>
    </parent>

    <groupId>tv.game88.core</groupId>
    <artifactId>game88-core</artifactId>
    <packaging>pom</packaging>

    <name>Game88 Server Core Parent</name>
    <description>88棋牌服务业务核心库</description>

    <modules>
        <module>game88-core-admin</module>
        <module>game88-core-admin-dict</module>
        <module>game88-core-config</module>
        <module>game88-core-member</module>
        <module>game88-core-session</module>
        <module>game88-core-quest</module>
        <module>game88-core-lottery</module>
        <module>game88-core-telegramBot</module>
        <module>game88-core-game</module>
        <module>game88-core-sms</module>
    </modules>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
